### ISSUE TITLE
word embedding dropout

### ISSUE THREAD

**Issue by bigsausage** [WenRichard/QACNN#1]
hello!
i've run your code and find that without the dropout of the word embedding, the model would behave badly.For about 0.58 of the MAP~but with the dropout ,i can get around 0.67 ~could you tell me is it a trick or it actually have some motivation behind?

**Comment by WenRichard** [comment]
dropout是一个可控制的超参数，它对模型是会产生一定的影响的；一般我们都会进行dropout来防止过拟合，不过不加dropout相差这么多个百分点是我没有想到的，总而言之，dropout可以看作是一个小trick，后期你还发现什么问题也欢迎与我交流！

**Comment by WenRichard** [comment]
> hello!
> i've run your code and find that without the dropout of the word embedding, the model would behave badly.For about 0.58 of the MAP~but with the dropout ,i can get around 0.67 ~could you tell me is it a trick or it actually have some motivation behind?

dropout是一个可控制的超参数，它对模型是会产生一定的影响的；一般我们都会进行dropout来防止过拟合，不过不加dropout相差这么多个百分点是我没有想到的，总而言之，dropout可以看作是一个小trick，后期你还发现什么问题也欢迎与我交流！
